UI/WebStore/Components/BreadCrumbsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;
using WebStore.Domain.ViewModels.BreadCrumbs;
using WebStore.Interfaces.Services;

namespace WebStore.Components
{
    public class BreadCrumbsViewComponent : ViewComponent
    {
        private readonly IProductData _ProductData;

        public BreadCrumbsViewComponent(IProductData ProductData) => _ProductData = ProductData;

        public IViewComponentResult Invoke(BreadCrumbsType Type, int id, BreadCrumbsType FromType)
        {
            if (!Enum.IsDefined(typeof(BreadCrumbsType), Type))
                throw new InvalidEnumArgumentException(nameof(Type), (int)Type, typeof(BreadCrumbsType));
            if (!Enum.IsDefined(typeof(BreadCrumbsType), FromType))
                throw new InvalidEnumArgumentException(nameof(FromType), (int)FromType, typeof(BreadCrumbsType));
            switch (Type)
            {

                default: throw new ArgumentOutOfRangeException(nameof(Type), Type, null);
                case BreadCrumbsType.None: break;
                case BreadCrumbsType.Section:
                    var section = _ProductData.GetSectionById(id);
                    return View(new[]
                    {
                        new BreadCrumbsViewModel
                        {
                            BreadCrumbsType = Type,
                            Id = id.ToString(),
                            Name = section.Name
                        }
                    });

                case BreadCrumbsType.Brand:
                    var brand = _ProductData.GetBrandById(id);
                    return View(new[]
                    {
                        new BreadCrumbsViewModel
                        {
                            BreadCrumbsType = Type,
                            Id = id.ToString(),
                            Name = brand.Name
                        }
                    });

                case BreadCrumbsType.Item:
                    return View(GetItemBreadCrumbs(id, FromType, Type));
            }
            return View(new BreadCrumbsViewModel[0]);
        }

        public IEnumerable<BreadCrumbsViewModel> GetItemBreadCrumbs(
            int id,
            BreadCrumbsType FromType,
            BreadCrumbsType Type)
        {

            var item = _ProductData.GetProductById(id);
            var crumbs = new List<BreadCrumbsViewModel>();
            if (FromType == BreadCrumbsType.Section)
                crumbs.Add(new BreadCrumbsViewModel
                {
                    BreadCrumbsType = FromType,
                    Id = id.ToString(),
                    Name = item.Section.Name
                });
            else

                crumbs.Add(new BreadCrumbsViewModel
                {
                    BreadCrumbsType = FromType,
                    Id = id.ToString(),
                    Name = item.Brand.Name
                });

            crumbs.Add(new BreadCrumbsViewModel
            {
                BreadCrumbsType = Type,
                Id = item.Id.ToString(),
                Name = item.Name
            });
            return crumbs;
        }
    }
}

UI/WebStore/Views/Shared/_Breadcrumbs.cshtml
@using WebStore.Controllers
@using WebStore.Domain.ViewModels.BreadCrumbs
@{
    Layout = "_Layout";
    var type = Context.Request.Query.ContainsKey("SectionId")
        ? BreadCrumbsType.Section
        : Context.Request.Query.ContainsKey("BrandId")
            ? BreadCrumbsType.Brand
            : BreadCrumbsType.None;
    var from_type = BreadCrumbsType.Section;
    if ((string)ViewContext.RouteData.Values["action"] == nameof(CatalogController.ProductDetails))
    {
        type = BreadCrumbsType.Item;
    }
    var id = 0;
    switch (type)
    {
        case BreadCrumbsType.None: break;
        case BreadCrumbsType.Section:
            id = int.Parse(Context.Request.Query["SectionId"].ToString());
            break;
        case BreadCrumbsType.Brand:
            id = int.Parse(Context.Request.Query["BrandId"].ToString());
            break;
        case BreadCrumbsType.Item:
            if (Context.Request.Query.ContainsKey("FromBrand"))
            {

                from_type = BreadCrumbsType.Brand;
            }
            id = int.Parse(ViewContext.RouteData.Values["id"].ToString());
            break;
        default:

            throw new ArgumentOutOfRangeException();
    }
}

@await Component.InvokeAsync("BreadCrumbs", new { Type = type, id, FromType = from_type })
@RenderBody()

@section Styles
{
    @RenderSection("Styles", false)
}

@section Scripts
{
    @RenderSection("Scripts", false)
}

UI/WebStore/Views/Shared/_Layout.cshtml
@{
    Layout = "_LayoutBase";
}

<div class="container">
    @RenderBody()
</div>


@section Styles
{
    @RenderSection("Styles", false)
}

@section Scripts
{
    @RenderSection("Scripts", false)
}

UI/WebStore/Views/Shared/_LayoutBase.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewBag.Title</title>

    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet">

    @*
        <link href="~/css/prettyPhoto.css" rel="styleshe8et" asp-append-version="true">
        <link href="~/css/price-range.css" rel="stylesheet" asp-append-version="true">
        <link href="~/css/animate.css" rel="stylesheet" asp-append-version="true">
        <link href="~/css/main.css" rel="stylesheet" asp-append-version="true">
        <link href="~/css/responsive.css" rel="stylesheet" asp-append-version="true">*@

    <environment include="Development">
        <link href="~/css/site.css" rel="stylesheet" asp-append-version="true">
    </environment>
    <environment exclude="Development">
        <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true">
    </environment>


    <!--[if lt IE 9]>
    <script src="~/js/html5shiv.js"></script>
    <![endif]-->
    @RenderSection("Styles", false)
</head><!--/head-->
<body>
    @await Html.PartialAsync("Partial/_Header")

    @RenderBody()

    @await Html.PartialAsync("Partial/_Footer")

    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.scrollUp.min.js"></script>
    <script src="~/js/Cart/CartLogic.js" asp-append-version="true"></script>
    <script src="~/js/jquery.prettyPhoto.js" asp-append-version="true"></script>

    <environment include="Development">
        @*<script src="~/js/price-range.js" asp-append-version="true"></script>
            <script src="~/js/main.js" asp-append-version="true"></script>*@

        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    <script >
        $(function () {
            Cart.init({
                addToCartLink: "@Url.Action("AddToCartAPI", "Cart")",
                getCartViewLink: "@Url.Action("GetCartViewApi", "Cart")",
                removeFromCartLink: "@Url.Action("RemoveFromCartApi", "Cart")",
                decrementLink: "@Url.Action("DecrementFromCartAPI", "Cart")"
            });
        });

    </script>

    @RenderSection("Scripts", false)
</body>
</html>

UI/WebStore/Views/Shared/_ValidationScripsPartial.cshtml
<environment names="Development">
    <script src="~/lib/jquery-validate/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
</environment>

<environment names="Staging,Production">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/jquery.validate.min.js"
            asp-fallback-src="~/lib/jquery-validate/jquery.validate.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.validator"
            crossorigin="anonymous"
            integrity="sha384-rZfj/ogBloos6wzLGpPkkOr/gpkBNLZ6b6yLy4o+ok+t/SAKlL5mvXLr0OXNi1Hp">
    </script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.9/jquery.validate.unobtrusive.min.js"
            asp-fallback-src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.validator && window.jQuery.validator.unobtrusive"
            crossorigin="anonymous"
            integrity="sha384-ifv0TYDWxBHzvAk2Z0n8R434FL1Rlv/Av18DXE43N/1rvHyOG4izKst0f2iSLdds">
    </script>
</environment>