UI/WebStore/Controllers/EmployesController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebStore.Domain.Models;
using WebStore.Interfaces.Services;

namespace WebStore.Controllers
{
    //[Route("Users/[action]")]
    [Authorize]
    public class EmployesController : Controller
    {
        private readonly IEmployeesData _EmployeesData;

        public EmployesController(IEmployeesData EmployeesData)
        {
            _EmployeesData = EmployeesData;
        }

        public IActionResult Index()
        {
            return View(_EmployeesData.GetAll());
        }

        //[Route("Info/{id}")]
        //[ActionName("EmployesDetails")]
        public IActionResult Details(int id)
        {
            var employe = _EmployeesData.GetById(id);
            if (employe == null)
                return NotFound();

            return View("EmployeeView", employe);
        }

        [Authorize(Roles = Domain.Entities.User.RoleAdmin)]
        public IActionResult Edit(int? id)
        {
            Employee employee;
            if (id != null)
            {
                employee = _EmployeesData.GetById((int)id);
                if (employee is null)
                    return NotFound();
            }
            else
            {
                employee = new Employee();
            }

            return View(employee);
        }

        [HttpPost]
        [Authorize(Roles = Domain.Entities.User.RoleAdmin)]
        public IActionResult Edit(Employee employee, [FromServices] IMapper mapper)
        {
            if(employee.Age < 18)
                ModelState.AddModelError("Age", "Возраст слишком маленький");

            if (employee.Age > 120)
                ModelState.AddModelError("Age", "Странный возраст");

            //if(employee.Age % 2 == 0)
            //    ModelState.AddModelError("", "Чётный возраст");

            if (!ModelState.IsValid) return View(employee);

            if (employee.Id > 0)
            {
                var db_employee = _EmployeesData.GetById(employee.Id);
                if (db_employee is null)
                    return NotFound();

                //AutoMapper.Mapper.Map(employee, db_employee);
                mapper.Map(employee, db_employee);

                //db_employee.FirstName = employee.FirstName;
                //db_employee.SurName = employee.SurName;
                //db_employee.Patronymic = employee.Patronymic;
                //db_employee.Age = employee.Age;
            }
            else
                _EmployeesData.AddNew(employee);

            _EmployeesData.SaveChanges();

            return RedirectToAction("Index");
        }

        [Authorize(Roles = Domain.Entities.User.RoleAdmin)]
        public IActionResult Delete(int id)
        {
            var employee = _EmployeesData.GetById(id);
            if (employee is null) return NotFound();
            _EmployeesData.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

UI/WebStore/Views/Employes/Details.cshtml
@model WebStore.Domain.Models.Employee

<h3>Карточка сотрдуника</h3>

<div>
    <p>Фамилия:</p>
    <p>@Model.SurName</p>
</div>

<div>
    <p>Имя:</p>
    <p>@Model.FirstName</p>
</div>

<div>
    <p>Отчество:</p>
    <p>@Model.Patronymic</p>
</div>

<div>
    <p>Возраст:</p>
    <p>@Model.Age</p>
</div>

<hr />

<a asp-controller="Employes" asp-action="Index">К списку сотрудников</a>

UI/WebStore/Views/Employes/Edit.cshtml
@model WebStore.Domain.Models.Employee
@{
    ViewData["Title"] = $"Редактирование сотрудника {(Model.Id == 0 ? (int?)null : Model.Id)}";
}

<h2>@ViewData["Title"]</h2>

<h4>Сотрдуник</h4>
<hr />

<div class="row">
    <div class="col-md-4">
        <form method="post" asp-controller="Employes" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*@Html.ValidationSummary(false, "Ошибка!", new { @class = "text-danger" })*@

            <input asp-for="Id" type="hidden" />

            <div class="form-group">
                <label asp-for="SurName" class="control-label"></label>
                <input asp-for="SurName" class="form-control" />
                <span asp-validation-for="SurName" class="text-danger"></span>
                @*@Html.ValidationMessageFor(m => m.SurName, "Ошибка!", new { @class = "text-danger" })*@
            </div>

            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Patronymic" class="control-label"></label>
                <input asp-for="Patronymic" class="form-control" />
                <span asp-validation-for="Patronymic" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Employes" asp-action="Index">Назад к списку</a>
</div>

@section Scripts{ 
    @await Html.PartialAsync("_ValidationScripsPartial")
}

UI/WebStore/Views/Employes/EmployeeView.cshtml
@model WebStore.Domain.Models.Employee

@{
    ViewData["Title"] = "EmployeeView";
}

<h2>EmployeeView</h2>

<div>
    <h4>Employee</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SurName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SurName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Patronymic)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Patronymic)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

UI/WebStore/Views/Employes/Index.cshtml
@model IEnumerable<WebStore.Domain.Models.Employee>

<h3>Сотрудники</h3>

<a asp-controller="Employes" asp-action="Edit" class="btn btn-default">Создать</a>

<hr/>
<table class="table table-hover">
    <thead>
        <tr>
            <th>ID</th>
            <th></th>
            <th>Фамилия</th>
            <th>Имя</th>
            <th>Отчество</th>
            <th>Возраст</th>
            <th></th>
            @if (User.IsInRole("Administrator"))
            {
                <th></th>
            }
        </tr>
    </thead>
    <tbody>
        @foreach (var employee in Model)
        {
            <tr>
                <td>@employee.Id</td>
                <td><a asp-controller="Employes" asp-action="Edit" asp-route-id="@employee.Id"><i class="fa fa-edit"></i></a></td>
                <td>@employee.SurName</td>
                <td>@employee.FirstName</td>
                <td>@employee.Patronymic</td>
                <td>@employee.Age</td>
                <td><a asp-controller="Employes" asp-action="Details" asp-route-id="@employee.Id">Детали</a></td>
                @if (User.IsInRole("Administrator"))
                {
                    <td>
                        <a asp-controller="Employes" asp-action="Delete" asp-route-id="@employee.Id">
                            <i class="fa fa-times text-danger"></i>
                        </a>
                    </td>
                }
            </tr>
        }
    </tbody>
</table>

<hr />